#!/usr/bin/env python3
"""Generate pinned numerical mass data; does not change legacy mass APIs."""
from pathlib import Path
import subprocess
from rdkit import Chem, rdBase

assert rdBase.rdkitVersion == '2025.09.6'
table = Chem.GetPeriodicTable()
lines = [
    '// Generated by scripts/gen_profile_weights.py with RDKit 2025.09.6.',
    '// Numerical periodic-table data from RDKit GetPeriodicTable().',
    '// https://github.com/rdkit/rdkit/blob/Release_2025_09_6/Code/GraphMol/atomic_data.cpp',
    '// Only mol_heavy_atom_mass uses this table; legacy weight APIs are unchanged.',
    'pub fn atom_mass(symbol: &str, isotope: Option<u16>) -> Option<f64> {',
    '    let &(z, average) = match symbol {',
]
for z in range(1,119):
    lines.append(f'        "{table.GetElementSymbol(z)}" => &({z}u16, {float(table.GetAtomicWeight(z))!r}),')
lines += [
    '        _ => return None,', '    };',
    '    match isotope.filter(|&i| i != 0) {',
    '        None => Some(average),',
    '        Some(i) => Some(ISOTOPES.binary_search_by_key(&(z, i), |&(z, i, _)| (z, i))',
    '            .map(|idx| ISOTOPES[idx].2).unwrap_or(0.0)),',
    '    }', '}',
    'const ISOTOPES: &[(u16, u16, f64)] = &[',
]
for z in range(1,119):
    for isotope in range(1,351):
        mass = table.GetMassForIsotope(z,isotope)
        if mass:
            lines.append(f'    ({z}, {isotope}, {mass!r}),')
lines += ['];', '']
out = Path(__file__).resolve().parents[1]/'crates/smiles/src/profile_weights.rs'
out.write_text('\n'.join(lines))
subprocess.run(['rustfmt', '--edition', '2021', str(out)], check=True)
print(out)
