# Resolve the Rust target used by DuckDB's native and cross-compilation jobs.
function(ducksmiles_select_rust_target OUTPUT_VARIABLE)
    set(SELECTED_TARGET "")
    if(DEFINED ENV{CARGO_TARGET} AND NOT "$ENV{CARGO_TARGET}" STREQUAL "")
        set(SELECTED_TARGET "$ENV{CARGO_TARGET}")
    elseif(DEFINED Rust_CARGO_TARGET AND NOT "${Rust_CARGO_TARGET}" STREQUAL "")
        # extension-ci-tools passes this for macOS and Windows cross builds.
        set(SELECTED_TARGET "${Rust_CARGO_TARGET}")
    elseif(EMSCRIPTEN OR CMAKE_SYSTEM_NAME STREQUAL "Emscripten"
           OR DUCKDB_EXPLICIT_PLATFORM MATCHES "^wasm_")
        set(SELECTED_TARGET "wasm32-unknown-emscripten")
    elseif(OSX_BUILD_ARCH STREQUAL "x86_64")
        set(SELECTED_TARGET "x86_64-apple-darwin")
    elseif(OSX_BUILD_ARCH STREQUAL "arm64")
        set(SELECTED_TARGET "aarch64-apple-darwin")
    elseif(DUCKDB_EXPLICIT_PLATFORM STREQUAL "osx_amd64")
        set(SELECTED_TARGET "x86_64-apple-darwin")
    elseif(DUCKDB_EXPLICIT_PLATFORM STREQUAL "osx_arm64")
        set(SELECTED_TARGET "aarch64-apple-darwin")
    elseif(DUCKDB_EXPLICIT_PLATFORM STREQUAL "linux_amd64"
           OR DUCKDB_EXPLICIT_PLATFORM STREQUAL "linux_amd64_gcc4")
        set(SELECTED_TARGET "x86_64-unknown-linux-gnu")
    elseif(DUCKDB_EXPLICIT_PLATFORM STREQUAL "linux_arm64")
        set(SELECTED_TARGET "aarch64-unknown-linux-gnu")
    elseif(DUCKDB_EXPLICIT_PLATFORM STREQUAL "linux_amd64_musl")
        set(SELECTED_TARGET "x86_64-unknown-linux-musl")
    elseif(DUCKDB_EXPLICIT_PLATFORM STREQUAL "linux_arm64_musl")
        set(SELECTED_TARGET "aarch64-unknown-linux-musl")
    elseif(DUCKDB_EXPLICIT_PLATFORM STREQUAL "windows_amd64")
        set(SELECTED_TARGET "x86_64-pc-windows-msvc")
    elseif(DUCKDB_EXPLICIT_PLATFORM STREQUAL "windows_amd64_mingw"
           OR DUCKDB_EXPLICIT_PLATFORM STREQUAL "windows_amd64_rtools")
        set(SELECTED_TARGET "x86_64-pc-windows-gnu")
    endif()
    set(${OUTPUT_VARIABLE} "${SELECTED_TARGET}" PARENT_SCOPE)
endfunction()
