cmake_minimum_required(VERSION 3.5...3.29)
include("${CMAKE_CURRENT_LIST_DIR}/SelectRustTarget.cmake")
set(ENV{CARGO_TARGET} "")

function(expect_target PLATFORM EXPECTED)
    set(DUCKDB_EXPLICIT_PLATFORM "${PLATFORM}")
    ducksmiles_select_rust_target(ACTUAL)
    if(NOT ACTUAL STREQUAL EXPECTED)
        message(FATAL_ERROR "${PLATFORM}: expected '${EXPECTED}', got '${ACTUAL}'")
    endif()
endfunction()

expect_target("" "")
expect_target(linux_amd64 x86_64-unknown-linux-gnu)
expect_target(linux_arm64 aarch64-unknown-linux-gnu)
expect_target(linux_amd64_gcc4 x86_64-unknown-linux-gnu)
expect_target(linux_amd64_musl x86_64-unknown-linux-musl)
expect_target(linux_arm64_musl aarch64-unknown-linux-musl)
expect_target(osx_amd64 x86_64-apple-darwin)
expect_target(osx_arm64 aarch64-apple-darwin)
expect_target(windows_amd64 x86_64-pc-windows-msvc)
expect_target(windows_amd64_mingw x86_64-pc-windows-gnu)
expect_target(windows_amd64_rtools x86_64-pc-windows-gnu)
foreach(PLATFORM wasm_mvp wasm_eh wasm_threads)
    expect_target(${PLATFORM} wasm32-unknown-emscripten)
endforeach()
set(CMAKE_SYSTEM_NAME Emscripten)
expect_target("" wasm32-unknown-emscripten)
unset(CMAKE_SYSTEM_NAME)
set(OSX_BUILD_ARCH arm64)
expect_target("" aarch64-apple-darwin)
set(Rust_CARGO_TARGET x86_64-pc-windows-gnu)
expect_target(osx_arm64 x86_64-pc-windows-gnu)
set(ENV{CARGO_TARGET} wasm32-unknown-emscripten)
expect_target(osx_arm64 wasm32-unknown-emscripten)
message(STATUS "Rust target selection: all cases passed")
